[icon]
prepend_conds = [
	{ if = "hidden & dir",  text = "ğŸ‘»" },  # Hidden directories
	{ if = "dir",           text = "ğŸ“" },  # Directories
	{ if = ".rs",           text = "ğŸ“" },  # Directories
	{ if = "!(dir | link)", text = "ğŸ“„" },  # Normal files (not directories or symlinks)
]

exts = [
	{ name = "rs", text = "ğŸ¦€" },
	{ name = "nim", text = "î™·" },
	{ name = "py", text = "îœ¼" },
]
